language: csharp
mono: none

git:
  autocrlf: true

solution: ORA.sln

jobs:
  include:
    - name: Windows
      os: windows
      before_install:
        - choco install dotnetcore-sdk

    - name: Linux
      os: linux
      dotnet: 3.1.100

install:
  - dotnet tool restore
  - dotnet restore

script:
  - dotnet build
  - dotnet format --check --dry-run --verbosity normal

after_success:
  - rm -rf send.sh
  - wget https://github.com/Crab-Wave/ora/raw/master/send.sh 
  - chmod +x send.sh
  - bash send.sh success $WEBHOOK_URL

after_failure:
  - rm -rf send.sh
  - https://github.com/Crab-Wave/ora/raw/master/send.sh
  - chmod +x send.sh
  - bash send.sh failure $WEBHOOK_URL

cache:
  directories:
    - '$HOME/.dotnet/tools'
