language: csharp
mono: none
dotnet: 3.1.100

solution: ORA.sln

jobs:
  include:
    - os: windows
    before_install:
    - choco install dotnetcore-sdk

    - os: linux
    dotnet: 3.1.100

# TODO: add test
install:
  - dotnet tool install -g dotnet-format
  - dotnet restore

script:
  - dotnet build

after_success:
  - dotnet-format --check --dry-run

cache:
  directories:
    - '$HOME/.dotnet/tools'
