language: csharp
mono: none
dotnet: 3.1.100

solution: ORA.sln

os:
  - windows
  - linux

# TODO: add test
install:
  - dotnet tool install -g dotnet-format
  - dotnet restore

script:
  - dotnet build

after_success:
  - dotnet format --check --dry-run

cache:
  directories:
    - '$HOME/.dotnet/tools'
