language: csharp
mono: none

solution: ORA.sln

jobs:
  include:
    - os: windows
      install:
        - choco install dotnetcore-sdk
        - dotnet tool install -g dotnet-format
        - dotnet restore

    - os: linux
      dotnet: 3.1.100
      install:
        - dotnet tool install -g dotnet-format || true
        - dotnet restore

script:
  - dotnet build

after_success:
  - dotnet-format --check --dry-run

cache:
  directories:
    - '$HOME/.dotnet/tools'
