language: csharp
mono: none

solution: ORA.sln

jobs:
  include:
    - os: windows
      before_install:
        - choco install dotnetcore-sdk

    - os: linux
      dotnet: 3.1.100

install:
  - dotnet tool install -g dotnet-format || true
  - dotnet restore

script:
  - dotnet build

after_success:
  - dotnet format --check --dry-run --verbosity n

cache:
  directories:
    - '$HOME/.dotnet/tools'
